version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: jboss/keycloak:10.0.1
    environment:
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - postgres
    volumes:
      - ./docker:/mnt
    ports:
      - 8080:8080
    security_opt:
      label: disable
